### ISSUE TITLE
About R2 in figure 3 of the paper

### ISSUE THREAD

**Issue by lucky9-cyou** [hahnyuan/RPTQ4LLM#13]
Hello, thank you so much for your outstanding project. I'm curious about whether the R2 operation is necessary. The query and key vectors are reorder vectors, which is then nullified by matrix multiplication. However, it appears we could achieve a similar outcome without using R2 at all.

![CleanShot 2024-04-19 at 22 40 13@2x](https://github.com/hahnyuan/RPTQ4LLM/assets/56758695/9f0fd780-b078-4c3d-990a-9989ef01d4b5)

**Comment by hahnyuan** [comment]
Thank you for your question. 
The activation vectors, including the query and key vectors, are quantized to reduce memory and computational requirements. The R2 operation, or the reordering operation, plays a role in optimizing the quantization of query and key vectors.

By applying the R2 operation, the activation vectors can be grouped in a way that benefits their quantization. This grouping can help improve the efficiency and accuracy of the quantization process, leading to better performance overall.

I hope this clarifies the importance of the R2 operation in the context you mentioned. If you have any further questions, feel free to ask!

**Comment by hahnyuan** [comment]
I plot a figure:
![image](https://github.com/hahnyuan/RPTQ4LLM/assets/13333830/62c43573-a0fb-41a1-a392-f7cac7802caa)

**Comment by lucky9-cyou** [comment]
You mean the R2 operator is for better Q*K results? Or it is for better Q vectors and K vectors?

**Comment by hahnyuan** [comment]
it is for better Q vectors and K vectors

**Comment by lucky9-cyou** [comment]
> it is for better Q vectors and K vectors

Got it. Thanks for your answer and outstanding project.
