### ISSUE TITLE
有配置perchannel的option选择吗？

### ISSUE THREAD

**Issue by wangshankun** [hahnyuan/RPTQ4LLM#6]
如果做成perchannel效果怎么样，是不是就不需要reorder了？

**Comment by hahnyuan** [comment]
per-channel可以做，但实际运算的开销太大，一般不认为这个是可行的方案---- 回复的原邮件 ----
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年5月10日 11:04
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [hahnyuan/RPTQ4LLM] 有配置perchannel的option选择吗？ (Issue #6)
        
      
    
  

如果做成perchannel效果怎么样，是不是就不需要reorder了？

**Comment by wangshankun** [comment]
> per-channel可以做，但实际运算的开销太大，一般不认为这个是可行的方案---- 回复的原邮件 ---- 发件人 ***@***.***> 发送日期 2023年5月10日 11:04 收件人 ***@***.***> 抄送人 ***@***.***> 主题 [hahnyuan/RPTQ4LLM] 有配置perchannel的option选择吗？ (Issue #6) 如果做成perchannel效果怎么样，是不是就不需要reorder了？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

perchannel和pertensor的计算量是一样的吧？ 甚至IO也几乎一样，怎么会开销变大了呢？

**Comment by wangshankun** [comment]
> per-channel一般只用于weight，activation的per-channel会把MAC operation的乘累加所有psum dequantize，这大大增加了计算开销。我这里引用一下谷歌量化白皮书： "We do not consider per-channel quantization for activations as this would complicate the inner product computations at the core of conv and matmul operations." [1] [1] Krishnamoorthi R. Quantizing deep convolutional networks for efficient inference: A whitepaper[J]. arXiv preprint arXiv:1806.08342, 2018.

不好意思，让您误解了，我本想表达的是weight的perchannel，翻论文后发现reorder是对activation做的操作的；
我还是惯性按照GPTQ来，本以为是对activation的量化操作，最终是通过补偿到weight的量化参数scale来实现的；

请教下，是否有这个可能呢？activation 采用pertensor的量化，而将多个cluster变成一个参数，其它的补偿融到weight的perchannel中，或者bias里面

**Comment by hahnyuan** [comment]
这个思路就是SmoothQuant [2]的做法，是有可能的。但我们试验过这样的方法，发现会对weight的量化产生较大影响，不能推进到4bit。weight的量化和activation的量化需要找到一个很好的平衡点。 [2]Xiao G, Lin J, Seznec M, et al. Smoothquant: Accurate and efficient post-training quantization for large language models[J]. arXiv preprint arXiv:2211.10438, 2022.

**Comment by wangshankun** [comment]
> 这个思路就是SmoothQuant [2]的做法，是有可能的。但我们试验过这样的方法，发现会对weight的量化产生较大影响，不能推进到4bit。weight的量化和activation的量化需要找到一个很好的平衡点。 [2]Xiao G, Lin J, Seznec M, et al. Smoothquant: Accurate and efficient post-training quantization for large language models[J]. arXiv preprint arXiv:2211.10438, 2022.

感谢！
想起来attention中matmul之后没有bias，这个和cnn不太一样；cnn的matmul之后有一个加上32bit的bias，这个 perchannel的bias应该可以容易的把activation给拉回来；这也能一定程度上解释为什么小模型的cnn会比大模型transformer更容易量化这个反直觉的操作

**Comment by brisker** [comment]
@hahnyuan 
如果RPTQ从static quantization 切换到dynamic quantization， 效果会好很多吗？
